### ISSUE TITLE
Firmware 1.5.5

### ISSUE THREAD

**Issue by ghost** [swap-dev/ledger-app-swap#1]
The TargetId needs to be changed to 0x31100004 for Firmware 1.5.5.

python -m ledgerblue.loadApp --path "2147483692/2147493991" --curve secp256k1 --tlv --targetId 0x31100004 --delete --fileName swap.hex --appName "Swap" --appVersion 1.0.1 --dataSize 0x00000280 --icon 0100000000ffffff000000e007f00ff81ffc3bce71fe7a7e7f7e7fbe7bce71fc3bf81ff00fe0070000 --appFlags 0x40

python -m ledgerblue.deleteApp --appName "Swap" --targetId 0x31100004

**Comment by sebseb7** [comment]
when the firmware version can be detected that can be incorporated in the single-click installer, otherwise it will be a two-click installer :-D

**Comment by RainbowMiner** [comment]
After the firmware update and the reinstall, the swap app does not work any more. If I click both ledger buttons to start the app and then press allow, it opens, but closes immediately.

**Comment by sebseb7** [comment]
https://github.com/swap-dev/ledger-app-swap/commit/de4daf4c090809978410d6455bf534416dc5b785

**Comment by RainbowMiner** [comment]
Thank you, but it is still not resolved. I am able to install the current release, clicking both buttons to start the app starts the question "Open non genuine app"+Indentifier. Pressing the right button to accept closes the Swap app.

**Comment by sebseb7** [comment]
To understands the problem I need to replicate it. My ledger is running 1.5.5 and it's working flawless. How to recreate the problem?

**Comment by sebseb7** [comment]
try this https://github.com/swap-dev/ledger-app-swap/tree/v1.1.1 and use the latest version of the ledgerblue python loader. works for me.

**Comment by RainbowMiner** [comment]
Setup: 
- Ledger Nano S with v1.5.5
- only the BitCoin App v1.3.7 installed on Ledger (I even tried without any app installed, too)
- Windows10, Python installed, Ledgerblue installed

![image](https://user-images.githubusercontent.com/39437538/53817737-772a8480-3f66-11e9-9c3d-2c6bcbbb6e45.png)
![image](https://user-images.githubusercontent.com/39437538/53817846-e99b6480-3f66-11e9-905f-060e9d75bae3.png)

Process:
- install Swap App via cmd, using the python command: ```python -m ledgerblue.loadApp --path "2147483692/2147493991" --curve secp256k1 --tlv --targetId 0x31100004 --delete --fileName swap.hex --appName "Swap" --appVersion 1.1.3 --dataSize 0x00000280 --icon 0100000000ffffff000000e007f00ff81ffc3bce71fe7a7e7f7e7fbe7bce71fc3bf81ff00fe0070000 --appFlags 0x40```

![image](https://user-images.githubusercontent.com/39437538/53818457-611dc380-3f68-11e9-80d2-75e24f9a79ae.png)
![image](https://user-images.githubusercontent.com/39437538/53818518-78f54780-3f68-11e9-9471-13729b813e04.png)
![image](https://user-images.githubusercontent.com/39437538/53818549-87dbfa00-3f68-11e9-9759-9c877b4bf6b8.png)
![image](https://user-images.githubusercontent.com/39437538/53818583-975b4300-3f68-11e9-9b02-c5c5dffad93d.png)
![image](https://user-images.githubusercontent.com/39437538/53818614-a3470500-3f68-11e9-90aa-a28aad211613.png)
![image](https://user-images.githubusercontent.com/39437538/53818634-af32c700-3f68-11e9-86a5-ad4f24fb314a.png)
![image](https://user-images.githubusercontent.com/39437538/53818664-bc4fb600-3f68-11e9-95a1-ba3b2d00715b.png)
![image](https://user-images.githubusercontent.com/39437538/53818711-cc679580-3f68-11e9-9c8e-33b204c3f78d.png)
After Entering the PIN Code ..
![image](https://user-images.githubusercontent.com/39437538/53818751-df7a6580-3f68-11e9-9aac-4f4473b03b98.png)
.. Swap is installed

Now starting with press on both buttons:
![image](https://user-images.githubusercontent.com/39437538/53818837-05076f00-3f69-11e9-957d-11cfbf64ea3c.png)
![image](https://user-images.githubusercontent.com/39437538/53818857-13558b00-3f69-11e9-9bdc-27e7297d5360.png)
.. pressing the right button to confirm leads to:
![image](https://user-images.githubusercontent.com/39437538/53818917-341de080-3f69-11e9-82bb-3b5427f1fc26.png)

Windows beeps connected / disconnected.



![image](https://user-images.githubusercontent.com/39437538/53817945-8231e480-3f67-11e9-973a-fb6151926834.png)

**Comment by RainbowMiner** [comment]
This is the ledgerblue loader, I am using:
![image](https://user-images.githubusercontent.com/39437538/53819117-94148700-3f69-11e9-85d7-2d158fd56373.png)

**Comment by RainbowMiner** [comment]
> try this https://github.com/swap-dev/ledger-app-swap/tree/v1.1.1 and use the latest version of the ledgerblue python loader. works for me.

Ok, I will try this version.

**Comment by RainbowMiner** [comment]
Uhh!! Nice, the v1.1.1 works 👍 Thank you very much!

**Comment by sebseb7** [comment]
nearly bricked my ledger with the 1.5.5 update X-D

**Comment by RainbowMiner** [comment]
I always get sweaty fingers during those firmware updates 😄 
.. even though I have got backup Ledger's.
