### ISSUE TITLE
[SOLVED] No longer working on Nano S Firmware 1.6.0

### ISSUE THREAD

**Issue by RainbowMiner** [swap-dev/ledger-app-swap#11]
The ledger app.hex can still be installed (with the same TargetId from 1.5.5), but when started, it hang's - the ledger needs to be disconnected and reconnected to get it back working.

Any idea what causes the trouble?

**Comment by RainbowMiner** [comment]
I have updated and recompiled the ledger app. There is a pull request avail.
The current "app.hex" file can be downloaded from [here](https://github.com/RainbowMiner/ledger-app-swap/releases/tag/v1.4.1), until the pull request is merged:

https://github.com/RainbowMiner/ledger-app-swap/releases/tag/v1.4.1

If you are happy with this work, consider sending me a cup of coffee with some XWP:

fh33cEdhKgx3rC6v931rEW3PQgoUJtuBuXT6ZN98tZii2jKtxkk67WBN93LjdngKuSUyWYBkagtQd4ajuZ7ZxoHs1HEPHZJVb

**Comment by Kryptoxic** [comment]
Thanks for the PR, I've looked at the code on ledger's repo and they've updated to 1.4.2 which I have merged with the master branch. The code has already been pushed and I'm currently trying to compile the app. Thanks again
