### ISSUE TITLE
No longer working on Nano S Firmware 2.0.0

### ISSUE THREAD

**Issue by RainbowMiner** [swap-dev/ledger-app-swap#14]
- the app can be installed with the given installation instructions on a Ledger Nano S with new firmware version 2.0.0
- when trying to open application, the Ledger Nano S freezes, nothing happens.

**Comment by Kryptoxic** [comment]
Updated code with ledger's code base and published a new release. Thanks for the notification and apologies for the late response.

**Comment by RainbowMiner** [comment]
Nice! Thank you!
